### ISSUE TITLE
Doesn't work on servers

### ISSUE THREAD

**Issue by ryleu** [dexman545/DatapackEasy#1]
It looks for a saves folder, but that doesn't exist on servers.

**Comment by dexman545** [comment]
Is there a point in using it on servers? There is only one possible datapack folder for them

**Comment by ryleu** [comment]
yes. i use it with packwiz for automatically updating modpacks on remote servers. makes it so i don't have to ssh or anything.

**Comment by dexman545** [comment]
Fix in 0.1.2
